//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.GASServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string l_MessageField;
        
        private bool l_ReturnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string l_Message {
            get {
                return this.l_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.l_MessageField, value) != true)) {
                    this.l_MessageField = value;
                    this.RaisePropertyChanged("l_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool l_Return {
            get {
                return this.l_ReturnField;
            }
            set {
                if ((this.l_ReturnField.Equals(value) != true)) {
                    this.l_ReturnField = value;
                    this.RaisePropertyChanged("l_Return");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GASServiceReference.GasServiceSoap")]
    public interface GasServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HMI.GASServiceReference.HelloWorldResponse HelloWorld(HMI.GASServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HMI.GASServiceReference.HelloWorldResponse> HelloWorldAsync(HMI.GASServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  p_Acc 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthByPassword", ReplyAction="*")]
        HMI.GASServiceReference.AuthByPasswordResponse AuthByPassword(HMI.GASServiceReference.AuthByPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthByPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HMI.GASServiceReference.AuthByPasswordResponse> AuthByPasswordAsync(HMI.GASServiceReference.AuthByPasswordRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  p_Acc 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        HMI.GASServiceReference.ChangePasswordResponse ChangePassword(HMI.GASServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HMI.GASServiceReference.ChangePasswordResponse> ChangePasswordAsync(HMI.GASServiceReference.ChangePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HMI.GASServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HMI.GASServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthByPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthByPassword", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.AuthByPasswordRequestBody Body;
        
        public AuthByPasswordRequest() {
        }
        
        public AuthByPasswordRequest(HMI.GASServiceReference.AuthByPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthByPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p_Acc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string p_PassWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string p_System;
        
        public AuthByPasswordRequestBody() {
        }
        
        public AuthByPasswordRequestBody(string p_Acc, string p_PassWd, string p_System) {
            this.p_Acc = p_Acc;
            this.p_PassWd = p_PassWd;
            this.p_System = p_System;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthByPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthByPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.AuthByPasswordResponseBody Body;
        
        public AuthByPasswordResponse() {
        }
        
        public AuthByPasswordResponse(HMI.GASServiceReference.AuthByPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthByPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HMI.GASServiceReference.CMessage AuthByPasswordResult;
        
        public AuthByPasswordResponseBody() {
        }
        
        public AuthByPasswordResponseBody(HMI.GASServiceReference.CMessage AuthByPasswordResult) {
            this.AuthByPasswordResult = AuthByPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(HMI.GASServiceReference.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p_Acc;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string p_Acc) {
            this.p_Acc = p_Acc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public HMI.GASServiceReference.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(HMI.GASServiceReference.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangePasswordResponseBody {
        
        public ChangePasswordResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GasServiceSoapChannel : HMI.GASServiceReference.GasServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GasServiceSoapClient : System.ServiceModel.ClientBase<HMI.GASServiceReference.GasServiceSoap>, HMI.GASServiceReference.GasServiceSoap {
        
        public GasServiceSoapClient() {
        }
        
        public GasServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GasServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HMI.GASServiceReference.HelloWorldResponse HMI.GASServiceReference.GasServiceSoap.HelloWorld(HMI.GASServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HMI.GASServiceReference.HelloWorldRequest inValue = new HMI.GASServiceReference.HelloWorldRequest();
            inValue.Body = new HMI.GASServiceReference.HelloWorldRequestBody();
            HMI.GASServiceReference.HelloWorldResponse retVal = ((HMI.GASServiceReference.GasServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HMI.GASServiceReference.HelloWorldResponse> HMI.GASServiceReference.GasServiceSoap.HelloWorldAsync(HMI.GASServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HMI.GASServiceReference.HelloWorldResponse> HelloWorldAsync() {
            HMI.GASServiceReference.HelloWorldRequest inValue = new HMI.GASServiceReference.HelloWorldRequest();
            inValue.Body = new HMI.GASServiceReference.HelloWorldRequestBody();
            return ((HMI.GASServiceReference.GasServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HMI.GASServiceReference.AuthByPasswordResponse HMI.GASServiceReference.GasServiceSoap.AuthByPassword(HMI.GASServiceReference.AuthByPasswordRequest request) {
            return base.Channel.AuthByPassword(request);
        }
        
        public HMI.GASServiceReference.CMessage AuthByPassword(string p_Acc, string p_PassWd, string p_System) {
            HMI.GASServiceReference.AuthByPasswordRequest inValue = new HMI.GASServiceReference.AuthByPasswordRequest();
            inValue.Body = new HMI.GASServiceReference.AuthByPasswordRequestBody();
            inValue.Body.p_Acc = p_Acc;
            inValue.Body.p_PassWd = p_PassWd;
            inValue.Body.p_System = p_System;
            HMI.GASServiceReference.AuthByPasswordResponse retVal = ((HMI.GASServiceReference.GasServiceSoap)(this)).AuthByPassword(inValue);
            return retVal.Body.AuthByPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HMI.GASServiceReference.AuthByPasswordResponse> HMI.GASServiceReference.GasServiceSoap.AuthByPasswordAsync(HMI.GASServiceReference.AuthByPasswordRequest request) {
            return base.Channel.AuthByPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HMI.GASServiceReference.AuthByPasswordResponse> AuthByPasswordAsync(string p_Acc, string p_PassWd, string p_System) {
            HMI.GASServiceReference.AuthByPasswordRequest inValue = new HMI.GASServiceReference.AuthByPasswordRequest();
            inValue.Body = new HMI.GASServiceReference.AuthByPasswordRequestBody();
            inValue.Body.p_Acc = p_Acc;
            inValue.Body.p_PassWd = p_PassWd;
            inValue.Body.p_System = p_System;
            return ((HMI.GASServiceReference.GasServiceSoap)(this)).AuthByPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HMI.GASServiceReference.ChangePasswordResponse HMI.GASServiceReference.GasServiceSoap.ChangePassword(HMI.GASServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public void ChangePassword(string p_Acc) {
            HMI.GASServiceReference.ChangePasswordRequest inValue = new HMI.GASServiceReference.ChangePasswordRequest();
            inValue.Body = new HMI.GASServiceReference.ChangePasswordRequestBody();
            inValue.Body.p_Acc = p_Acc;
            HMI.GASServiceReference.ChangePasswordResponse retVal = ((HMI.GASServiceReference.GasServiceSoap)(this)).ChangePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HMI.GASServiceReference.ChangePasswordResponse> HMI.GASServiceReference.GasServiceSoap.ChangePasswordAsync(HMI.GASServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HMI.GASServiceReference.ChangePasswordResponse> ChangePasswordAsync(string p_Acc) {
            HMI.GASServiceReference.ChangePasswordRequest inValue = new HMI.GASServiceReference.ChangePasswordRequest();
            inValue.Body = new HMI.GASServiceReference.ChangePasswordRequestBody();
            inValue.Body.p_Acc = p_Acc;
            return ((HMI.GASServiceReference.GasServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
    }
}
