//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DMS_SUBSCRIBE_USER
    {
        public string USER_ID { get; set; }
        public string SUB_TYPE { get; set; }
        public string ROLE_ID { get; set; }
        public bool SUB_METHOD { get; set; }
        public System.DateTime SUBSCRIBE_TIME { get; set; }
        public bool PRE_SUB { get; set; }
        public string INFORM_CASE { get; set; }
    }
}
