//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DMS_PROPERTY_LIMIT
    {
        public string FOLDER_ID { get; set; }
        public bool DOC_NAME { get; set; }
        public bool DOC_SERIAL { get; set; }
        public bool PUBLISH_UNIT { get; set; }
        public bool CUSTODY_USER { get; set; }
        public bool DOC_COMMENT { get; set; }
        public bool DOC_KEYWORD { get; set; }
        public bool DOC_TYPE { get; set; }
        public bool DOC_REFLINK { get; set; }
    }
}
