//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DMS_DOC_SHADOW
    {
        public string DOC_ID { get; set; }
        public string SYS_VERSION { get; set; }
        public string MANUAL_VERSION { get; set; }
        public string FILE_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_SERIAL { get; set; }
        public string CUSTODY_USER { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOC_STATUS { get; set; }
        public string PUBLISH_UNIT { get; set; }
        public string DOC_COMMENT { get; set; }
        public string VERSION_COMMENT { get; set; }
        public string DOC_AUTHOR { get; set; }
        public decimal DOC_VER_GRADE { get; set; }
        public int DOC_GRADE_COUNT { get; set; }
        public bool APPLY_DUPLICATE { get; set; }
        public bool COMMON_EDIT { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
        public string SECRET_RANK { get; set; }
        public string SOURCE_CONTROL { get; set; }
        public System.DateTime ACTIVE_DAY { get; set; }
        public System.DateTime INVALID_DAY { get; set; }
        public string PDF_ID { get; set; }
        public string ACTIVE_STATUS { get; set; }
        public Nullable<int> DL_NUM { get; set; }
        public string APPROVE_USER { get; set; }
        public string DOC_KEYWORD { get; set; }
        public string APPROVE_TYPE { get; set; }
        public string WKF_TASKID { get; set; }
        public Nullable<bool> SECRET_DEFINE { get; set; }
        public string CHECKOUT_USER { get; set; }
        public string VOID_USER { get; set; }
        public Nullable<bool> IS_VOID { get; set; }
        public Nullable<System.DateTime> PUBLISH_DATE { get; set; }
    }
}
