//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DMS_DOC_PROPERTY
    {
        public string DOC_ID { get; set; }
        public string FOLDER_ID { get; set; }
        public bool VER_MANUAL_CONTROL { get; set; }
        public string EDIT_SYS_VERSION { get; set; }
        public string PUBLISH_SYS_VERSION { get; set; }
        public string PUBLISH_MANUAL_VERSION { get; set; }
        public string EDIT_MANUAL_VERSION { get; set; }
        public decimal DOC_AVG_GRADE { get; set; }
        public string PRE_EDIT_MANUAL_VERSION { get; set; }
        public string PRE_EDIT_SYS_VERSION { get; set; }
        public int DOC_GRADE_NUM { get; set; }
    }
}
