//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DMS_REMOTE_UPLOAD
    {
        public string REMOTE_UPLOAD_ID { get; set; }
        public string EVENT_ID { get; set; }
        public string DOC_ID { get; set; }
        public string EDIT_SYS_VERSION { get; set; }
        public string FILE_ID { get; set; }
        public string STATUS { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> EXE_COUNT { get; set; }
        public string REMOTE_SITE { get; set; }
        public string REMOTE_FOLDER_PATH { get; set; }
        public string UPLOAD_PARAMETERS { get; set; }
        public string CREATE_USER { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
