//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_RPT_ABN_PUNCH
    {
        public string USER_GUID { get; set; }
        public string GROUP_GUID { get; set; }
        public System.DateTime DATE { get; set; }
        public string TYPE { get; set; }
        public string STATUS { get; set; }
        public decimal EXP_WORK_HOURS { get; set; }
        public int EXP_OFF_TIME { get; set; }
        public decimal PUN_WORK_HOURS { get; set; }
        public decimal PUN_ABN_HOURS { get; set; }
        public int PUN_LATE_MIN { get; set; }
        public decimal ACT_WORK_HOURS { get; set; }
        public decimal ACT_ABN_HOURS { get; set; }
        public int ACT_LATE_MIN { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
    }
}
