//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_CUS_CUSTOMER_FIELD
    {
        public string CUSTOMER_ID { get; set; }
        public string OPTION1 { get; set; }
        public string OPTION1_VALUE { get; set; }
        public string OPTION2 { get; set; }
        public string OPTION2_VALUE { get; set; }
        public string OPTION3 { get; set; }
        public string OPTION3_VALUE { get; set; }
        public string OPTION4 { get; set; }
        public string OPTION4_VALUE { get; set; }
        public string OPTION5 { get; set; }
        public string OPTION5_VALUE { get; set; }
        public string OPTION6 { get; set; }
        public string OPTION6_VALUE { get; set; }
    }
}
