//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_LEAVE
    {
        public string LEA_CODE { get; set; }
        public string NAME { get; set; }
        public decimal DAYS { get; set; }
        public string CALCULATED { get; set; }
        public bool SEPARATE { get; set; }
        public int MIN_UNIT { get; set; }
        public int TYPE { get; set; }
        public int GENDER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string DEDUCT_SALARY { get; set; }
        public Nullable<bool> CONSECUTIVE { get; set; }
        public Nullable<int> BEF_LEAVE_SPACE { get; set; }
        public Nullable<int> AFT_LEAVE_SPACE { get; set; }
    }
}
