//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_CUS_CUSTOMER
    {
        public string CUSTOMER_ID { get; set; }
        public string INDUSTRY_ID { get; set; }
        public string GRADE_ID { get; set; }
        public string CUSTOMER_ABBREVIATION { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_ENGLISH_NAME { get; set; }
        public string OWNER { get; set; }
        public Nullable<int> CAPITALIZATION { get; set; }
        public string COMPANY_FAX { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string COMPANY_ZIP_CODE { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string INVOICE_ZIP_CODE { get; set; }
        public string INVOICE_ADDRESS { get; set; }
        public string WEB_URL { get; set; }
        public string RM_ID { get; set; }
        public string UNIFIED_ID { get; set; }
        public string CONFIRM_PUBLISH { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_FROM { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string MODIFY_FROM { get; set; }
        public string AREA_ID { get; set; }
        public Nullable<System.DateTime> PUBLISH_DATE { get; set; }
    }
}
