//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_EMPL_HR_LICENSE
    {
        public string LICE_GUID { get; set; }
        public string USER_GUID { get; set; }
        public int YEAR { get; set; }
        public string LICENSE_GUID { get; set; }
        public string GRADE { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.DateTime> ACQU_DATE { get; set; }
        public Nullable<System.DateTime> EFFE_DATE { get; set; }
        public string REMARKS { get; set; }
        public string FILE_GROUP { get; set; }
    }
}
