//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_EMPL_HR
    {
        public string USER_GUID { get; set; }
        public bool MARRIED { get; set; }
        public string FAITH { get; set; }
        public string BLOOD { get; set; }
        public string CONSTELLATION { get; set; }
        public string PERMANENT_ADDR { get; set; }
        public string PERMANENT_ZIP { get; set; }
        public string PERMANENT_PHONE { get; set; }
        public string PRESENT_ADDR { get; set; }
        public string PRESENT_ZIP { get; set; }
        public string PRESENT_PHONE { get; set; }
        public string EMER_CONTACT { get; set; }
        public string EMER_PHONE1 { get; set; }
        public string EMER_PHONE2 { get; set; }
        public string EMER_MOBILE { get; set; }
        public string PAYROLL_BANK { get; set; }
        public string PAYROLL_ACC { get; set; }
        public string PAYROLL_FILE { get; set; }
        public string JOB_TYPE { get; set; }
        public string IDENTITY_TYPE { get; set; }
        public string IDENTITY_FILE { get; set; }
        public string MILITARY_SERVICE { get; set; }
        public string MILITARY_DUTY { get; set; }
        public string MILITARY_TYPE { get; set; }
        public string MILITARY_RANK { get; set; }
        public Nullable<System.DateTime> MILITARY_FROM { get; set; }
        public Nullable<System.DateTime> MILITARY_TO { get; set; }
        public string MILITARY_FILE { get; set; }
        public string CARD_NO { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public string COST_CENTER_ID { get; set; }
        public string BU { get; set; }
    }
}
