//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_DOMAIN
    {
        public string DOMAIN_GUID { get; set; }
        public string DOMAIN_NAME { get; set; }
        public string DOMAIN_NICKNAME { get; set; }
        public Nullable<bool> DEFAULT_DOMAIN { get; set; }
        public string FULLY_DOMAIN_NAME { get; set; }
    }
}
