//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_FILE_PROXY
    {
        public int PROXY_INDEX { get; set; }
        public string NAME { get; set; }
        public string URL { get; set; }
        public bool DISABLE { get; set; }
        public string CRATE_USER { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_FROM { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string MODIFY_FROM { get; set; }
    }
}
