//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_SETTING
    {
        public string GROUP_GUID { get; set; }
        public decimal M_OVERTIME_HOURS { get; set; }
        public decimal F_OVERTIME_HOURS { get; set; }
        public int LATE_MIN { get; set; }
        public int LATE_TIMES { get; set; }
        public decimal A_WORK_HOURS { get; set; }
        public decimal H_WORK_HOURS { get; set; }
    }
}
