//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_MESSAGE_QUENE
    {
        public string QUENE_GUID { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string BODY { get; set; }
        public string TITLE { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public string BCC { get; set; }
        public string CC { get; set; }
        public Nullable<System.DateTime> SEND_TIME { get; set; }
        public Nullable<int> CURRENT_TRY_COUNT { get; set; }
        public Nullable<System.DateTime> LAST_TRY_TIME { get; set; }
    }
}
