//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_TEMP
    {
        public System.Guid PUNCH_TEMP_ID { get; set; }
        public string CARD_NO { get; set; }
        public System.DateTime PUNCH_TIME { get; set; }
        public string TYPE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string CLOCK_CODE { get; set; }
    }
}
