//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_CUS_CONTACT
    {
        public string CONTACT_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string SEX { get; set; }
        public string DEPARTMENT { get; set; }
        public string TITLE { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string DIRECTOR { get; set; }
        public string ASSISTANT { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EXT_NUM { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string SKYPE { get; set; }
        public string MSN { get; set; }
        public string YAHOO { get; set; }
        public string QQ { get; set; }
        public string ADDRESS { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_FROM { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string MODIFY_FROM { get; set; }
        public string EBACCOUNT { get; set; }
    }
}
