//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SLOGAN
    {
        public string SLOGAN_ID { get; set; }
        public string SLOGAN_NO { get; set; }
        public string SLOGAN_CONTENT { get; set; }
        public string LINK_URL { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<bool> ALLOW_EXTERNAL { get; set; }
        public string FILE_GROUP_ID { get; set; }
    }
}
