//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_FILE_STORE
    {
        public string FILE_GROUP_ID { get; set; }
        public string FILE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
        public string FILE_CONTENT_TYPE { get; set; }
        public int FILE_LENGTH { get; set; }
        public bool IS_ORIGINAL_NAME { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<System.DateTime> LAST_USE_TIME { get; set; }
        public bool IS_ENCRYPTION { get; set; }
        public string CREATE_USER { get; set; }
        public bool DELETED { get; set; }
        public string DELETED_USER { get; set; }
        public Nullable<System.DateTime> DELETED_TIME { get; set; }
        public int LOCATION { get; set; }
        public string R_SITE_ID { get; set; }
    }
}
