//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_MEMB
    {
        public string USER_GUID { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_FAX { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_SERIAL { get; set; }
        public string EXT_NUM { get; set; }
        public string GROUP_ID { get; set; }
        public string PHONE { get; set; }
        public string PHOTO { get; set; }
        public string SEX { get; set; }
        public string SINGNATURE { get; set; }
        public string SKYPE { get; set; }
        public string QQ { get; set; }
        public string MSN { get; set; }
        public string YAHOO { get; set; }
        public string MOBILE { get; set; }
    }
}
