//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_MENU
    {
        public string MENU_ID { get; set; }
        public string PARENT_MENU_ID { get; set; }
        public string LINK_URL { get; set; }
        public bool IS_NEW_WINDOW { get; set; }
        public string NORMAL_ICON_URL { get; set; }
        public string MOUSE_OVER_ICON_URL { get; set; }
        public string TYPE { get; set; }
        public string DATA_KEY { get; set; }
        public Nullable<int> ORDERS { get; set; }
    }
}
