//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_USER_SCALABLE
    {
        public string USER_SCALABLE_GUID { get; set; }
        public string USER_GUID { get; set; }
        public int YEAR { get; set; }
        public string TASK_ID { get; set; }
        public string DOC_NBR { get; set; }
        public int USED_DAYS { get; set; }
        public string CREATOR { get; set; }
        public string CREATER_FROM { get; set; }
        public System.DateTime CREATER_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODIFY_FROM { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
    }
}
