//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_DUTY_FORM_ALLOWANCE
    {
        public string TASK_ID { get; set; }
        public string ALLOWANCE_GUID { get; set; }
        public string APPLICANT { get; set; }
        public string OWNER { get; set; }
        public string DOC_NBR { get; set; }
        public string STATUS { get; set; }
        public string CLASS_GUID { get; set; }
        public string ALLOWANCE_CODE { get; set; }
        public string ALLOWANCE_NAME { get; set; }
        public decimal COMPANY_AMOUNT { get; set; }
        public decimal COMMITTEE_AMOUNT { get; set; }
        public decimal SUB_TOTAL_AMOUNT { get; set; }
        public decimal ADDITIONAL_AMOUNT { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public string ALLOWANCE_REMARK { get; set; }
        public decimal APPLY_COUNT { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public Nullable<System.DateTime> COMPANY_ALLOT_DATE { get; set; }
        public Nullable<System.DateTime> COMMITTEE_ALLOT_DATE { get; set; }
        public string CREATOR { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
