//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SCH_PERS_HOLIDAY
    {
        public bool ALL_DAY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string HOLIDAY_GUID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string SUBJECT { get; set; }
        public string OWNER { get; set; }
    }
}
