//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SCH_WORK_HOURS
    {
        public decimal FRIDAY { get; set; }
        public string GROUP_ID { get; set; }
        public decimal MONDAY { get; set; }
        public decimal SATURDAY { get; set; }
        public decimal SUNDAY { get; set; }
        public decimal THURSDAY { get; set; }
        public decimal TUESDAY { get; set; }
        public decimal WEDNESDAY { get; set; }
    }
}
