//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SCH_REPEAT
    {
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public bool IS_EXPIRE { get; set; }
        public string REPEAT_GUID { get; set; }
        public Nullable<int> REPEAT_TIMES { get; set; }
        public string REPEAT_TYPE { get; set; }
    }
}
