//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_TASK
    {
        public string EVENT_ID { get; set; }
        public string FILE { get; set; }
        public string TYPE { get; set; }
        public System.DateTime EXECUTE_TIME { get; set; }
        public string STATE { get; set; }
        public int TIME_OUT { get; set; }
        public System.DateTime LAST_STATE_TIME { get; set; }
        public string PRAMA { get; set; }
        public string RESULT { get; set; }
    }
}
