//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_USER
    {
        public string USER_GUID { get; set; }
        public string ACCOUNT { get; set; }
        public string NAME { get; set; }
        public string LANG { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public bool IS_PASSWORD_RESET { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public bool IS_LOCKED_OUT { get; set; }
        public Nullable<System.DateTime> LAST_ACTIVITY_DATE { get; set; }
        public Nullable<System.DateTime> LAST_LOCKED_OUT_DATE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PASSWORD_CHANGE_DATE { get; set; }
        public string USER_TYPE { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public string THEME { get; set; }
        public string MSG_TYPE { get; set; }
        public Nullable<bool> IS_AD_AUTH { get; set; }
        public string EMAIL_A { get; set; }
        public string EMAIL_B { get; set; }
        public string EMAIL_C { get; set; }
        public string EMAIL_D { get; set; }
        public int PASSWORD_INVALID_ATTEMPTS { get; set; }
        public int PW_RESET_REASON { get; set; }
        public Nullable<bool> IS_USB_AUTH { get; set; }
        public string USB_KEY { get; set; }
        public bool IS_SUSPENDED { get; set; }
        public Nullable<System.DateTime> LAST_SUSPENDED_DATE { get; set; }
        public string SID { get; set; }
        public string OPTION1 { get; set; }
        public string OPTION2 { get; set; }
        public string OPTION3 { get; set; }
        public string OPTION4 { get; set; }
        public string OPTION5 { get; set; }
        public string OPTION6 { get; set; }
        public string PERSONAL1 { get; set; }
        public string PERSONAL2 { get; set; }
        public string PERSONAL3 { get; set; }
        public string PERSONAL4 { get; set; }
        public string PERSONAL5 { get; set; }
        public string PERSONAL6 { get; set; }
        public string NICKNAME { get; set; }
        public string CA_SERIAL_NUM { get; set; }
        public int PROXY { get; set; }
        public string DOMAIN { get; set; }
    }
}
