//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SCH_MEETING
    {
        public string BORROW_GUID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string LOCATION { get; set; }
        public string MEETING_GUID { get; set; }
        public string PERSONAL_TYPE { get; set; }
        public string USER_SET { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string SUBJECT { get; set; }
        public string OWNER { get; set; }
        public string CHAIR { get; set; }
        public string REAL_ATTEND_USER { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public string CONTACT_PERSON { get; set; }
        public Nullable<bool> IS_LIVE_MEETING { get; set; }
        public string VIRTUAL_MEETING_ID { get; set; }
        public string USE_BORROW_ROOM { get; set; }
        public string REPEAT_GUID { get; set; }
        public string IS_REPEAT { get; set; }
    }
}
