//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_FORUM_ARTICLE
    {
        public string ARTICLE_GUID { get; set; }
        public string SUBJECT { get; set; }
        public string CONTEXT { get; set; }
        public string ANNOUNCER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public string MODIFY_USER { get; set; }
        public string TOPIC_GUID { get; set; }
        public string STATE { get; set; }
        public int FLOOR { get; set; }
    }
}
