//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_CUS_EVENT_LOG
    {
        public string LOG_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CONTACT_NAME { get; set; }
        public string EVENT_TYPE { get; set; }
        public string EVENT_ACTION { get; set; }
        public Nullable<System.DateTime> EVENT_TIME { get; set; }
        public string EVENT_USER { get; set; }
        public string EVENT_FROM { get; set; }
        public string CONFIRM_PUBLISH { get; set; }
    }
}
