//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_REMOTE_COPY_RECORD
    {
        public string RECORD_ID { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public string FILE_ID { get; set; }
        public string ORIGIN_FILE_ID { get; set; }
        public Nullable<bool> IS_COPY_SUCCESS { get; set; }
        public string REMARK { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_FROM { get; set; }
    }
}
