//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EB_EMPL_HR_FAMILY
    {
        public string USER_GUID { get; set; }
        public string FATHER_NAME { get; set; }
        public string FATHER_AGE { get; set; }
        public Nullable<System.DateTime> FATHER_BIRTHDAY { get; set; }
        public string FATHER_JOB { get; set; }
        public string MOTHER_NAME { get; set; }
        public string MOTHER_AGE { get; set; }
        public Nullable<System.DateTime> MOTHER_BIRTHDAY { get; set; }
        public string MOTHER_JOB { get; set; }
        public string SPOUSE_NAME { get; set; }
        public string SPOUSE_AGE { get; set; }
        public Nullable<System.DateTime> SPOUSE_BIRTHDAY { get; set; }
        public string SPOUSE_JOB { get; set; }
        public string OLDER_SIB_COUNT { get; set; }
        public string YOUNGER_SIB_COUNT { get; set; }
        public string CHILDREN_COUNT { get; set; }
    }
}
