//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_SCH_HOLIDAY_TT
    {
        public string HOLIDAY_GUID { get; set; }
        public int WORK_TIME { get; set; }
        public int WORK_TIME_ET { get; set; }
        public int WORK_TIME_LT { get; set; }
        public int OFF_TIME { get; set; }
        public int OFF_TIME_ET { get; set; }
        public int OFF_TIME_LT { get; set; }
        public int LUNCH_TIME_BT { get; set; }
        public int LUNCH_TIME_ET { get; set; }
        public decimal WORK_HOUR { get; set; }
    }
}
