//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EIP_PLANT
    {
        public string CLASS_GUID { get; set; }
        public string CUSTODIAN { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
        public string NAME { get; set; }
        public string PLANT_GUID { get; set; }
        public string SERIAL_NO { get; set; }
        public string PLANT_STATE { get; set; }
        public Nullable<bool> PLANT_OPEN { get; set; }
    }
}
