//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_ASSESS_GENERAL
    {
        public string TASK_ID { get; set; }
        public string SITE_CODE { get; set; }
        public string GUID { get; set; }
        public string SMID { get; set; }
        public string SIGNER { get; set; }
        public string ASSESS_TYPE { get; set; }
        public Nullable<int> EFFICIENCY { get; set; }
        public Nullable<int> EFFICIENCY_Y { get; set; }
        public Nullable<int> PERFORMANCE { get; set; }
        public Nullable<int> PERFORMANCE_Y { get; set; }
        public Nullable<int> ATTITUDE { get; set; }
        public Nullable<int> ATTITUDE_Y { get; set; }
        public Nullable<int> PROVISION { get; set; }
        public Nullable<int> PROVISION_Y { get; set; }
        public Nullable<int> SPIRIT { get; set; }
        public Nullable<int> SPIRIT_Y { get; set; }
        public Nullable<int> TIDY { get; set; }
        public Nullable<int> TIDY_Y { get; set; }
        public Nullable<int> COORDINATION { get; set; }
        public Nullable<int> COORDINATION_Y { get; set; }
        public Nullable<int> SPECIALTY { get; set; }
        public Nullable<int> SPECIALTY_Y { get; set; }
        public Nullable<int> REACTION { get; set; }
        public Nullable<int> REACTION_Y { get; set; }
        public Nullable<int> Staff_Car { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Total_Y { get; set; }
        public string RANK { get; set; }
        public string RANK_Y { get; set; }
        public string EDIT_DATE { get; set; }
    }
}
