//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_ResignationPaper
    {
        public string Sid { get; set; }
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OnDutyDate { get; set; }
        public System.DateTime OffDutyDate { get; set; }
        public string Unit { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public string Reason { get; set; }
        public string Memo { get; set; }
    }
}
