//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_ASSESS_ASSISTAN_MANAGER
    {
        public string TASK_ID { get; set; }
        public string SITE_CODE { get; set; }
        public string SIGNER { get; set; }
        public string GUID { get; set; }
        public string SMID { get; set; }
        public string ASSESS_TYPE { get; set; }
        public Nullable<int> KPI_Performance { get; set; }
        public Nullable<int> KPI_Performance_Y { get; set; }
        public Nullable<int> KPI_Ploy { get; set; }
        public Nullable<int> KPI_Ploy_Y { get; set; }
        public Nullable<int> KPI_Improve { get; set; }
        public Nullable<int> KPI_Improve_Y { get; set; }
        public Nullable<int> Cooperation { get; set; }
        public Nullable<int> Cooperation_Y { get; set; }
        public Nullable<int> Subordinate { get; set; }
        public Nullable<int> Subordinate_Y { get; set; }
        public Nullable<int> Risk { get; set; }
        public Nullable<int> Risk_Y { get; set; }
        public Nullable<int> Communication { get; set; }
        public Nullable<int> Communication_y { get; set; }
        public Nullable<int> Attitude { get; set; }
        public Nullable<int> Attitude_Y { get; set; }
        public Nullable<int> Staff_Car { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> TOTAL_Y { get; set; }
        public string RANK { get; set; }
        public string RANK_Y { get; set; }
        public string EDIT_DATE { get; set; }
    }
}
