//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_ASSESS_STAFF
    {
        public string TASK_ID { get; set; }
        public string SITE_CODE { get; set; }
        public string GUID { get; set; }
        public string SMID { get; set; }
        public string SIGNER { get; set; }
        public string ASSESS_TYPE { get; set; }
        public Nullable<int> KNOWLEDGE { get; set; }
        public Nullable<int> KNOWLEDGE_Y { get; set; }
        public Nullable<int> FORCE { get; set; }
        public Nullable<int> FORCE_Y { get; set; }
        public Nullable<int> SENSE { get; set; }
        public Nullable<int> SENSE_Y { get; set; }
        public Nullable<int> INTERGITY { get; set; }
        public Nullable<int> INTERGITY_Y { get; set; }
        public Nullable<int> EXECUTION { get; set; }
        public Nullable<int> EXECUTION_Y { get; set; }
        public Nullable<int> ABILITY { get; set; }
        public Nullable<int> ABILITY_Y { get; set; }
        public Nullable<int> EQ { get; set; }
        public Nullable<int> EQ_Y { get; set; }
        public Nullable<int> Staff_Car { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Total_Y { get; set; }
        public string RANK { get; set; }
        public string RANK_Y { get; set; }
        public string EDIT_DATE { get; set; }
    }
}
