//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_ASSESS_SERVICE
    {
        public string TASK_ID { get; set; }
        public string SITE_CODE { get; set; }
        public string GUID { get; set; }
        public string YEAR { get; set; }
        public string SMID { get; set; }
        public string SIGNER { get; set; }
        public string ASSESS_TYPE { get; set; }
        public string NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string FUNC_NAME { get; set; }
        public string TITLE_NAME { get; set; }
        public string ACCOUNT { get; set; }
        public string CREATE_DATE { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> TOTAL_Y { get; set; }
        public string RANK { get; set; }
        public string RANK_Y { get; set; }
        public string EDIT_DATE { get; set; }
        public string MEMO { get; set; }
    }
}
