//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_Nuclear_Salary
    {
        public string TASK_ID { get; set; }
        public string NS_GUID { get; set; }
        public string USER_GUID { get; set; }
        public string CLASS { get; set; }
        public string MOVE_DATE { get; set; }
        public string MOVE_TYPE { get; set; }
        public string SINGER { get; set; }
        public string MEMO { get; set; }
        public string NS_Year { get; set; }
        public string NS_Month { get; set; }
        public string M_Movetype { get; set; }
        public Nullable<System.DateTime> Creat_Date { get; set; }
        public Nullable<double> Labor_Protectoin { get; set; }
        public Nullable<double> Health_Insurance { get; set; }
        public Nullable<double> Labor_Pension { get; set; }
        public Nullable<double> Group_Insurance { get; set; }
        public Nullable<double> Buraden_Sum { get; set; }
        public string Posting_Year { get; set; }
        public string Posting_Number { get; set; }
        public string Other_Move { get; set; }
        public string Group_Name { get; set; }
        public string TITLE_NAME { get; set; }
        public string OPTION1 { get; set; }
        public Nullable<double> Base_Salary { get; set; }
        public Nullable<double> Food_Allowance { get; set; }
        public Nullable<double> Full_Bonus { get; set; }
        public Nullable<double> Position_Bonus { get; set; }
        public Nullable<double> Learder_Bonus { get; set; }
        public Nullable<double> Skill_Bonus { get; set; }
        public Nullable<double> License_Bonus { get; set; }
        public Nullable<double> Experience_Bonus { get; set; }
        public Nullable<double> Other_Bonus { get; set; }
        public Nullable<double> Bonus_Sum { get; set; }
    }
}
