//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HR_WORKTIME
    {
        public int GUID { get; set; }
        public string NAME { get; set; }
        public string ACCOUNT { get; set; }
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public string DAY { get; set; }
        public string TIME_GO_TO_WORK { get; set; }
        public string TIME_OFF_WORK { get; set; }
        public string OPPS1 { get; set; }
        public string OPPS2 { get; set; }
        public string OPPS3 { get; set; }
        public string OPPS4 { get; set; }
        public string FIRST3_NUMBER { get; set; }
        public string AFTER4_NUMBER { get; set; }
        public string CARD_NUMBER { get; set; }
        public string R_TIME_GO_TO_WORK { get; set; }
        public string R_TIME_OFF_WORK { get; set; }
        public string INSTER_TIME { get; set; }
        public string INSTER_USER { get; set; }
        public string YMD { get; set; }
    }
}
