//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KD_ORDERS
    {
        public string OrderNo { get; set; }
        public string BranchId { get; set; }
        public string SectorId { get; set; }
        public Nullable<System.DateTime> OrderDay { get; set; }
        public Nullable<System.DateTime> SaleDay { get; set; }
        public Nullable<System.DateTime> DispatchDay { get; set; }
        public Nullable<System.DateTime> RegisterDay { get; set; }
        public Nullable<System.DateTime> PromiseDay { get; set; }
        public Nullable<System.DateTime> appointday { get; set; }
        public Nullable<System.DateTime> DeliverDay { get; set; }
        public Nullable<System.DateTime> ModifyDay { get; set; }
        public string Memo { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string Status { get; set; }
        public string CustomerId { get; set; }
        public string CarOwnerId { get; set; }
        public string SMId { get; set; }
        public string EngNo { get; set; }
        public string CarCod { get; set; }
        public string CarMdl { get; set; }
        public string SFX { get; set; }
        public Nullable<double> shm { get; set; }
        public bool Valid { get; set; }
        public bool SelfDelivery { get; set; }
        public string ordpnm { get; set; }
        public string oadcd { get; set; }
        public string oaddr { get; set; }
        public string ortelh { get; set; }
        public string orsubh { get; set; }
        public string ortelo { get; set; }
        public string orsubo { get; set; }
        public string offcnm { get; set; }
        public string sp { get; set; }
        public Nullable<int> PrePay { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<short> changed { get; set; }
        public string yeartype { get; set; }
        public Nullable<System.DateTime> promisetime { get; set; }
        public string Hengno { get; set; }
        public Nullable<System.DateTime> Hdispatchday { get; set; }
        public Nullable<System.DateTime> PriorityDay { get; set; }
        public int Comi4 { get; set; }
        public int Comi5 { get; set; }
        public int Comi6 { get; set; }
        public string ContractOrderNo { get; set; }
    }
}
