//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KD_CAR
    {
        public string EngNo { get; set; }
        public string FrameNo { get; set; }
        public string LicenseNo { get; set; }
        public string KeyNo { get; set; }
        public Nullable<System.DateTime> MadeDay { get; set; }
        public Nullable<System.DateTime> ArrivalDay { get; set; }
        public Nullable<System.DateTime> LeaveDay { get; set; }
        public string StorePosition { get; set; }
        public string CertificatePosition { get; set; }
        public string SFX { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
        public string CarCod { get; set; }
        public string CarMdl { get; set; }
        public string yearType { get; set; }
        public string DstBst { get; set; }
        public Nullable<decimal> addcomi { get; set; }
        public Nullable<short> badcarstate { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> ArvBranchDay { get; set; }
        public Nullable<short> transtatus { get; set; }
        public string arrivaltime { get; set; }
        public string Dlrcd { get; set; }
    }
}
