//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PET_FINANCE
    {
        public string ID { get; set; }
        public string ORDERNO { get; set; }
        public int SEVERAL { get; set; }
        public System.DateTime PAY_DATE { get; set; }
        public string TYPE { get; set; }
        public System.DateTime EDIT_DATE { get; set; }
        public string CREATE_FROM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATOR { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
