//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PET_PETITION
    {
        public string ORDERNO { get; set; }
        public string SMID { get; set; }
        public string PET_TYPE { get; set; }
        public string COM_NAME { get; set; }
        public string COM_PHONE { get; set; }
        public string COM_ADD { get; set; }
        public string COM_ID { get; set; }
        public Nullable<System.DateTime> COM_DATE { get; set; }
        public string PEO_NAME { get; set; }
        public Nullable<int> PEO_SEX { get; set; }
        public string PEO_ID { get; set; }
        public Nullable<int> PEO_MERRY { get; set; }
        public string PEO_PHONE { get; set; }
        public string PEO_MOBILE { get; set; }
        public Nullable<System.DateTime> PEO_BIRTHDAY { get; set; }
        public string PEO_ADD { get; set; }
        public string PEO_REPORT_ADD { get; set; }
        public string SER_NAME { get; set; }
        public string SER_ADD { get; set; }
        public Nullable<int> SER_YEAR { get; set; }
        public string SER_JOB { get; set; }
        public string SER_PHONE { get; set; }
        public string HOUSE_ADD { get; set; }
        public string HOUSE_NUM { get; set; }
        public string HOUSE_BUILD { get; set; }
        public string HOUSE_NAME { get; set; }
        public string HOUSE_ID { get; set; }
        public double CREDIT_MONEY { get; set; }
        public double CREDIT_PHASES { get; set; }
        public double MONTH_MONEY { get; set; }
        public double SUBSIDIES_MONEY { get; set; }
        public double PET_RATE { get; set; }
        public double PET_SEVERAL { get; set; }
        public double PET_MONEY { get; set; }
        public double PET_SUBSIDIES { get; set; }
        public int PAY_TYPE { get; set; }
        public int CAR_REASON { get; set; }
        public int CAR_USER { get; set; }
        public string PET_RESULT { get; set; }
        public int STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string PET_COM { get; set; }
        public Nullable<System.DateTime> PET_BDATE { get; set; }
        public Nullable<System.DateTime> PET_EDATE { get; set; }
        public string PET_SUPID { get; set; }
        public Nullable<System.DateTime> KD_SEND_DATE { get; set; }
        public Nullable<System.DateTime> KD_OUT_DATE { get; set; }
        public Nullable<System.DateTime> KD_IN_DATE { get; set; }
        public string KD_NUM { get; set; }
        public Nullable<int> CLOSE_TYPE { get; set; }
        public string INVOICE { get; set; }
        public string CLOSE_MEMO { get; set; }
        public string TASK_ID { get; set; }
        public string DOC_NBR { get; set; }
        public Nullable<int> TASK_RESULT { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string DELETER { get; set; }
        public string CAR_TYPE { get; set; }
        public string TYPE { get; set; }
        public string TELVIEW { get; set; }
        public string TRACK { get; set; }
        public string LicenseBack { get; set; }
        public Nullable<System.DateTime> LicenseBackDate { get; set; }
    }
}
