//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PMS_TASK_REPORT_BACK
    {
        public string RB_GUID { get; set; }
        public string TASK_GUID { get; set; }
        public int STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PROGRESS_RATE { get; set; }
        public string REPORTER { get; set; }
        public System.DateTime REPORT_TIME { get; set; }
        public string FILE_GROUP_ID { get; set; }
    }
}
