//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PMS_AUDIT
    {
        public string AUDIT_GUID { get; set; }
        public string TARGET_PROJ_GUID { get; set; }
        public string TARGET_SERIES_GUID { get; set; }
        public string TARGET_TASK_GUID { get; set; }
        public int AUDIT_TYPE { get; set; }
        public string AUDITOR { get; set; }
        public string SENDER { get; set; }
        public Nullable<bool> OUTCOME { get; set; }
        public string OPINION { get; set; }
        public Nullable<System.DateTime> AUDIT_TIME { get; set; }
        public System.DateTime SEND_TIME { get; set; }
    }
}
