//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PMS_PROJECT
    {
        public string PROJ_GUID { get; set; }
        public string PROJ_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public string AUDITOR_RM_ID { get; set; }
        public string PM_RM_ID { get; set; }
        public int STATUS { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string WORK_SET { get; set; }
        public string VIEWER_RM_ID { get; set; }
        public Nullable<System.DateTime> EXPECT_START_DATE { get; set; }
        public Nullable<System.DateTime> EXPECT_END_DATE { get; set; }
        public Nullable<System.DateTime> PRACTICAL_START_TIME { get; set; }
        public Nullable<System.DateTime> PRACTICAL_END_TIME { get; set; }
    }
}
