//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUE_ITEM
    {
        public string ITEM_GUID { get; set; }
        public string DESIGN_MASTER_GUID { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_TYPE { get; set; }
        public string IS_REQUIRED { get; set; }
        public string RepeatDirection { get; set; }
        public Nullable<int> RepeatColumns { get; set; }
        public string IS_CREATE_OTHER { get; set; }
        public Nullable<int> TEXTBOX_HEIGHT { get; set; }
        public string MEMO { get; set; }
        public string ORDER { get; set; }
        public Nullable<int> MAX_ANS_COUNT { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
    }
}
