//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUE_DESIGN_M
    {
        public string DESIGN_MASTER_GUID { get; set; }
        public string DESIGN_NAME { get; set; }
        public string CATEGORY_GUID { get; set; }
        public string DESIGN_STATUS { get; set; }
        public string IS_PUBLISH { get; set; }
        public string IS_REGISTERED { get; set; }
        public string IS_ALLOW_COPY { get; set; }
        public string IS_ALLOW_SAVE { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public string QUE_HEADER { get; set; }
        public string QUE_FOOTER { get; set; }
        public string MEMO { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public string IS_REPEAT_SUBMIT { get; set; }
        public string IS_MODIFY { get; set; }
    }
}
