//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUE_MASTER
    {
        public string QUS_MASTER_GUID { get; set; }
        public string DESIGN_MASTER_GUID { get; set; }
        public string QUS_MASTER_STATUS { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string USER_SET { get; set; }
        public string IS_SEND_NOTICE { get; set; }
        public Nullable<int> SEND_COUNT { get; set; }
        public Nullable<int> SUBMIT_COUNT { get; set; }
        public string REPORT_USER_SET { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public Nullable<System.DateTime> SUSPEND_DATE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRED_DATE { get; set; }
        public Nullable<System.DateTime> SHOW_REPORT_DATE { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
    }
}
