//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REW_SALEDOC
    {
        public string ORDERNO { get; set; }
        public string INSURANCE_COM_ITEM { get; set; }
        public double INSURANCE_NUM { get; set; }
        public int OLDCAR { get; set; }
        public string INSURANCE_ITME { get; set; }
        public string INVOICE_FILE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATOR { get; set; }
        public int STATUS { get; set; }
        public Nullable<double> DISCOUNT_MONEY { get; set; }
        public Nullable<double> SUBSIDIES_MONEY { get; set; }
        public Nullable<double> INVOICE_MONEY { get; set; }
    }
}
