//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REW_SPECIALSALE
    {
        public string ORDERNO { get; set; }
        public int INSURANCE_TYPE { get; set; }
        public int SPECIAL_TYPE { get; set; }
        public double APPLY_NUM { get; set; }
        public double DISCOUNT { get; set; }
        public int PAY_TYPE { get; set; }
        public int BIG_TYPE { get; set; }
        public string MEMO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATOR { get; set; }
        public int STATUS { get; set; }
        public string TASK_ID { get; set; }
        public string DOC_NBR { get; set; }
        public Nullable<int> TASK_RESULT { get; set; }
        public Nullable<double> SUPPORT_MONEY { get; set; }
        public Nullable<int> SUPPORT_TYPE { get; set; }
        public Nullable<int> LAST_MONTH { get; set; }
        public Nullable<int> SPECIAL_MONEY { get; set; }
        public Nullable<int> PART_MONEY { get; set; }
        public Nullable<double> M_APPLY_NUM { get; set; }
    }
}
