//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REW_QA
    {
        public string ID { get; set; }
        public string ORDERNO { get; set; }
        public string CREATOR { get; set; }
        public string TYPE { get; set; }
        public string QUESTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ANSER { get; set; }
        public Nullable<System.DateTime> ANSER_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CLOSEMONTH { get; set; }
    }
}
