//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REW_BASEAWARD
    {
        public string ID { get; set; }
        public string DOC_NO { get; set; }
        public string CAR_CODE { get; set; }
        public string CAR_MDL { get; set; }
        public string CAR_SFX { get; set; }
        public string CAR_YEAR { get; set; }
        public double ADD_POINT_AMT { get; set; }
        public double MODIFY_PRICE { get; set; }
        public double BASEAWARD { get; set; }
        public double HARDCOVER_PRICE { get; set; }
        public System.DateTime BDATE { get; set; }
        public System.DateTime EDATE { get; set; }
        public string CREATE_FROM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATOR { get; set; }
        public string MODIFY_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<double> APPLY_NUM { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY { get; set; }
        public Nullable<double> APPLY_NUM_25 { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_25 { get; set; }
        public Nullable<double> APPLY_NUM_GET { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_GET { get; set; }
        public Nullable<double> APPLY_NUM_IM { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_IM { get; set; }
        public Nullable<double> APPLY_NUM_TIC { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_TIC { get; set; }
        public Nullable<double> APPLY_NUM_25IM { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_25IM { get; set; }
        public Nullable<double> APPLY_NUM_25TIC { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_25TIC { get; set; }
        public Nullable<double> APPLY_NUM_RES { get; set; }
        public Nullable<double> APPLY_NUM_EMPTY_RES { get; set; }
    }
}
