//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TONER_PROJECT
    {
        public int f_prono { get; set; }
        public string f_proname { get; set; }
        public Nullable<double> f_stock { get; set; }
        public double f_price { get; set; }
        public string f_companyid { get; set; }
        public string f_editday { get; set; }
        public string f_memo { get; set; }
    }
}
