//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_CUST_SITE
    {
        public string FLOW_ID { get; set; }
        public string SITE_ID { get; set; }
        public string PREV_SITE_ID { get; set; }
        public string NEXT_SITE_ID { get; set; }
        public Nullable<int> TIMEOUT_COUNT { get; set; }
        public Nullable<int> SIGN_TYPE { get; set; }
        public string GENERAL_SIGNERS { get; set; }
        public string ALERT_SIGNERS { get; set; }
        public Nullable<bool> IS_MODIFIABLE { get; set; }
        public string SIGNED_ALTER { get; set; }
        public Nullable<int> SITE_TYPE { get; set; }
    }
}
