//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_TASK
    {
        public string TASK_ID { get; set; }
        public Nullable<int> TASK_SEQ { get; set; }
        public Nullable<System.DateTime> BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<int> TASK_STATUS { get; set; }
        public Nullable<int> TASK_RESULT { get; set; }
        public string DOC_NBR { get; set; }
        public int FLOW_TYPE { get; set; }
        public string FLOW_ID { get; set; }
        public string FORM_VERSION_ID { get; set; }
        public string SOURCE_DOC_ID { get; set; }
        public string CURRENT_DOC_ID { get; set; }
        public Nullable<int> FORM_STATUS { get; set; }
        public string USER_GUID { get; set; }
        public string USER_GROUP_ID { get; set; }
        public string USER_JOB_TITLE_ID { get; set; }
        public string ATTACH_ID { get; set; }
        public Nullable<int> URGENT_LEVEL { get; set; }
        public string CURRENT_SIGNER { get; set; }
        public int LOCK_STATUS { get; set; }
        public string CURRENT_DOC { get; set; }
        public Nullable<bool> FILING_STATUS { get; set; }
        public string CURRENT_SITE_ID { get; set; }
        public Nullable<bool> IS_APPLICANT_GETBACK { get; set; }
        public string APPLICANT_COMMENT { get; set; }
        public string DISPLAY_TITLE { get; set; }
        public string MESSAGE_CONTENT { get; set; }
        public string DEFAULT_IQY_USERS { get; set; }
        public string AGENT_USER { get; set; }
        public string CANCEL_FORM_REASON { get; set; }
    }
}
