//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_ENDFORMCALLBACK_WS
    {
        public string WS_ID { get; set; }
        public string WS_NAME { get; set; }
        public string WS_URL { get; set; }
        public string WS_METHOD { get; set; }
        public int WS_AUTH { get; set; }
        public string WS_ACCOUNT { get; set; }
        public string WS_PASSWORD { get; set; }
        public string CREATE_USERGUID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODIFY_USERGUID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
