//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_FORM
    {
        public string FORM_ID { get; set; }
        public string FORM_NAME { get; set; }
        public string CATEGORY_ID { get; set; }
        public string USING_VERSION_ID { get; set; }
        public Nullable<decimal> DELAY_HOUR { get; set; }
        public string FORM_RM_ID { get; set; }
        public string ARCHIVE_RM_ID { get; set; }
        public Nullable<bool> FORM_CTL { get; set; }
        public Nullable<bool> REJECT_TO_ARCHIVE { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public bool CALLBACK_FLAG { get; set; }
        public string CALLBACK_WEBSERVICE { get; set; }
        public string CALLBACK_WEBSERVICE_METHOD { get; set; }
        public bool CALLBACK_CONTENT_FLAG { get; set; }
        public bool CALLBACK_COMMNET_FLAG { get; set; }
        public string MODULE_ID { get; set; }
        public string CALLBACK_ID { get; set; }
        public int IS_EXTERNAL_FORM { get; set; }
        public bool IS_ONLINE_RA { get; set; }
        public bool ALLOWMODIFY { get; set; }
        public bool ALLOWAPPLICENTMODIFY { get; set; }
        public bool ALLOWOTHERMODIFY { get; set; }
        public string ALLOWMODIFYUSERSET { get; set; }
        public bool RA_CALLWS_FLAG { get; set; }
        public string RA_CALLWS_ID { get; set; }
        public bool RA_CONTENT_FLAG { get; set; }
        public bool RA_COMMENT_FLAG { get; set; }
        public string START_FORM_TRIGGER_GUID { get; set; }
        public string END_FORM_TRIGGER_GUID { get; set; }
        public string CHANGE_FORM_RESULT_GUID { get; set; }
        public string RESPONSIBLE_CONTROL { get; set; }
        public string READER_RM_ID { get; set; }
        public string RESPONSIBLE_RM_ID { get; set; }
        public Nullable<bool> DELETE_SCRIPT { get; set; }
        public Nullable<bool> BATCH_SIGN { get; set; }
        public Nullable<bool> IQY_FLAG { get; set; }
        public Nullable<bool> ALLOW_RETURN_SIGN { get; set; }
        public Nullable<bool> ALLOW_EXCEPTION_SEND { get; set; }
        public Nullable<bool> ALLOW_AGENT_APPLICANTION { get; set; }
        public Nullable<bool> SEND_SAME_DEPT { get; set; }
        public Nullable<bool> SAVE_SCRIPT { get; set; }
        public Nullable<int> OR_FUNCTION_SET { get; set; }
        public Nullable<bool> SET_AGENT { get; set; }
        public string SET_AGENT_USERSET { get; set; }
        public string FORM_NAME_CULTURE { get; set; }
        public Nullable<int> ALLOW_ADDITIONAL_SIGN { get; set; }
        public string SIGN_FORM_TRIGGER_GUID { get; set; }
        public string RETURN_FORM_VALIDATOR_TRIGGER { get; set; }
        public string CHANGE_RESULT_VALIDATOR_TRIGGER { get; set; }
        public string DISPLAY_MULTI_UNSIGN_USER { get; set; }
        public string BACK_IMAGE_USE { get; set; }
        public string BACK_IMAGE_FILEGROUP_ID { get; set; }
        public Nullable<bool> PRINT_AUTH { get; set; }
        public string PRINT_USER_SET { get; set; }
        public Nullable<bool> WS_ENDFORM_VALIDATE_FLAG { get; set; }
        public string WS_ENDFORM_VALIDATE_ID { get; set; }
        public Nullable<bool> WS_ENDFORM_VALIDATE_CONTENT { get; set; }
        public Nullable<bool> WS_ENDFORM_VALIDATE_COMMENT { get; set; }
        public string FORM_INFO { get; set; }
    }
}
