//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_FORM_VERSION_MAIL_FORMAT
    {
        public string FORM_VERSION_ID { get; set; }
        public string CULTURE { get; set; }
        public int ALERT_TYPE { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public Nullable<bool> DEFAULT { get; set; }
    }
}
