//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_EXTERNAL_TASK
    {
        public string EXTERNAL_TASK_ID { get; set; }
        public string FORM_INFO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string EXTERNAL_FORM_NBR { get; set; }
        public string DOC_NBR { get; set; }
        public string TASK_ID { get; set; }
        public string EXCEPTION_MSG { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_FROM { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string EXTERNAL_REMARK { get; set; }
        public Nullable<int> TASK_RESULT { get; set; }
        public string RETURN_VALUE { get; set; }
    }
}
