//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_FORM_CONDITION
    {
        public string COND_ID { get; set; }
        public int COND_ATTRIBUTE { get; set; }
        public string FORM_VERSION_ID { get; set; }
        public int COMBINE_TYPE { get; set; }
        public Nullable<int> COMBIN_OP { get; set; }
        public Nullable<int> LEFT_TYPE { get; set; }
        public string LEFT_VALUE { get; set; }
        public Nullable<int> LEFT_OP { get; set; }
        public Nullable<int> CENTER_TYPE { get; set; }
        public string CENTER_VALUE { get; set; }
        public Nullable<int> RIGHT_OP { get; set; }
        public Nullable<int> RIGHT_TYPE { get; set; }
        public string RIGHT_VALUE { get; set; }
        public string RIGHT_XMLVALUE { get; set; }
        public string CENTER_TAG { get; set; }
    }
}
