//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_SCRIPT
    {
        public string SCRIPT_ID { get; set; }
        public string SCRIPT_NAME { get; set; }
        public string USER_GUID { get; set; }
        public string FORM_ID { get; set; }
        public string FORM_VERSION_ID { get; set; }
        public string COMMENT { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> STATE { get; set; }
        public string GROUP_ID { get; set; }
        public string FILE_GROUP_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public Nullable<bool> IS_USED { get; set; }
        public string DISPLAY_TITLE { get; set; }
        public string MESSAGE_CONTENT { get; set; }
        public Nullable<bool> IS_IQY { get; set; }
        public string DEFAULT_IQY_USERS { get; set; }
        public string AGENT_USER { get; set; }
        public string PERSONAL_ATTACH_ID { get; set; }
    }
}
