//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_SITE_CONDITION_NOTIFY
    {
        public string NOTIFY_ID { get; set; }
        public string FORM_VERSION_ID { get; set; }
        public string SITE_ID { get; set; }
        public string COND_ID { get; set; }
        public Nullable<int> NOTIFY_TYPE { get; set; }
        public Nullable<bool> IS_APPLYER_ALERT { get; set; }
        public Nullable<bool> IS_APPLYER_SUPERIOR_ALERT { get; set; }
        public Nullable<bool> IS_LAST_AGENT_ALERT { get; set; }
        public Nullable<bool> IS_LAST_SUPERIOR_ALERT { get; set; }
        public string ALERT_GENERAL_SIGNERS { get; set; }
    }
}
