//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_TASK_SITE_TEMP
    {
        public string TASK_ID { get; set; }
        public string SRC_SITE_ID { get; set; }
        public string ALERTER_USER_SET { get; set; }
        public string SIGNER_USER_SET { get; set; }
        public Nullable<int> SIGN_TYPE { get; set; }
        public Nullable<int> TIMEOUT_COUNT { get; set; }
        public string CONDITION_ID { get; set; }
        public string NEXT_DEF_SITE_ID { get; set; }
        public Nullable<bool> IS_MASTER_SITE { get; set; }
        public string SRC_PARENT_SITE_ID { get; set; }
        public string SUB_FLOW_ID { get; set; }
        public Nullable<int> SUB_FLOW_TYPE { get; set; }
        public string SUB_FLOW_NAME { get; set; }
        public string START_GROUP_ID { get; set; }
        public string START_JOB_TITLE_ID { get; set; }
        public System.DateTime MODIFY_TIME { get; set; }
        public Nullable<int> SITE_KIND { get; set; }
    }
}
