//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_TASK_NODE
    {
        public string SITE_ID { get; set; }
        public int NODE_SEQ { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> FINISH_TIME { get; set; }
        public Nullable<int> NODE_STATUS { get; set; }
        public Nullable<int> SIGN_STATUS { get; set; }
        public string ORIGINAL_SIGNER { get; set; }
        public string ACTUAL_SIGNER { get; set; }
        public string DOC_ID { get; set; }
        public string COMMENT { get; set; }
        public int DOC_MODIFY_FLAG { get; set; }
        public Nullable<int> IS_AGENT { get; set; }
        public string AGENT_USER_GUID { get; set; }
        public Nullable<System.DateTime> AGENT_START_TIME { get; set; }
        public Nullable<System.DateTime> AGENT_FINISH_TIME { get; set; }
        public Nullable<bool> IS_GETBACK { get; set; }
        public string MODIFY_FIELD { get; set; }
        public Nullable<System.DateTime> TIMEOUT_SEND_TIME { get; set; }
        public string SIGNER_INFO_SNAPSHOT { get; set; }
        public string ATTACH_ID { get; set; }
        public string ORIGINAL_SIGNER_INFO { get; set; }
    }
}
