//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_FORM_VERSION
    {
        public string FORM_VERSION_ID { get; set; }
        public string FORM_ID { get; set; }
        public decimal VERSION { get; set; }
        public Nullable<bool> ENABLE_FLOW { get; set; }
        public string FLOW_ID { get; set; }
        public Nullable<bool> ISSUE_CTL { get; set; }
        public Nullable<System.DateTime> ISSUE_TIME { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string VERSION_FIELD { get; set; }
        public Nullable<int> VERSION_NUM_TYPE { get; set; }
        public Nullable<bool> IS_ALLOW_ISSUE { get; set; }
        public bool IS_USE { get; set; }
        public string DISPLAY_FIELD { get; set; }
        public string DISPLAY_TITLE { get; set; }
        public string VALIDATOR_WS_ID { get; set; }
        public string NORMAL_WS_ID { get; set; }
        public string WS_FIELDS { get; set; }
        public string BATCHFIELDS { get; set; }
    }
}
