//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WKF_TASK_TRIGGER_RECORD
    {
        public string RECORD_ID { get; set; }
        public string TASK_ID { get; set; }
        public string TRIGGER_ID { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public int STATUS { get; set; }
        public string FORM_TYPE { get; set; }
        public int SEND_COUNT { get; set; }
        public string FORM_ID { get; set; }
        public string SITE_ID { get; set; }
        public string SITE_CODE { get; set; }
    }
}
